services:
  cinny:
    networks:
      - cinny-network
  matrix-nginx:
    container_name: matrix-nginx
    image: nginx
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-80}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    networks:
      - cinny-network
      - step-ca-network

configs:
  nginx-config:
    content: |
      user nginx;
      worker_processes auto;
      error_log /var/log/nginx/error.log;
      pid /run/nginx.pid;

      events {
        worker_connections 16384;
        multi_accept on;
        use epoll;
      }
      http {
        server {
          server_name ${VIRTUAL_HOST};
          listen      80 default_server;

          location /.well-known/matrix/server {
            return 200 '{"m.server": "${VIRTUAL_HOST}:443"}';
            types { } default_type "application/json; charset=utf-8";
          }

          location /.well-known/matrix/client {
            return 200 '{"m.homeserver": {"base_url": "https://${VIRTUAL_HOST}"}}';
            types { } default_type "application/json; charset=utf-8";
            add_header "Access-Control-Allow-Origin" *;
          }

          location ~ ^/_matrix/(.*)$ {
            proxy_pass http://${BACKEND_DOMAIN};
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
            proxy_set_header X-Forwarded-Host $$host;
          }

          location / {
            proxy_pass http://${FRONTEND_DOMAIN};
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $$scheme;
            proxy_set_header X-Forwarded-Host $$host;
          }
        }
      }

networks:
  cinny-network:
    name: cinny-network
    driver: bridge
  step-ca-network:
    external: true
